---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata: 
  labels: 
    k8s-app: fluentd-es
  name: fluentd-es-v1.22
  namespace: kube-system
spec: 
#  selector: 
#    k8s-app: fluentd-es
#    version: v1.22
  template: 
    metadata: 
      labels: 
        k8s-app: fluentd-es
        version: v1.22
    spec: 
      containers: 
        - image: 'tintoy.azurecr.io/daas/fluentd:1.0.0-dev' # gcr.io/google_containers/fluentd-elasticsearch:1.22
          imagePullPolicy: Always
          name: fluentd-es
          command: 
            - /bin/sh
            - "-c"
            - "/usr/sbin/td-agent 2>&1 >> /var/log/fluentd.log"
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: 'elasticsearch-logging.kube-system.svc.cluster.local'
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: '9200'
          resources: 
            limits: 
              memory: 200Mi
            requests: 
              cpu: 100m
              memory: 200Mi
          volumeMounts: 
            - 
              mountPath: /var/log
              name: varlog
            - 
              mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
      volumes: 
        - 
          hostPath: 
            path: /var/log
          name: varlog
        - 
          hostPath: 
            path: /var/lib/docker/containers
          name: varlibdockercontainers
      imagePullSecrets:
          - name: daas-registry
