---
- include: "{{ playbook_dir }}/playbooks/check-requirements.yml"

- hosts: all
  roles:
    - common
  tags:
    - common

- hosts: role=storage-host
  vars:
    initial_nfs_volume: /dev/sdb
    nfs_volume_size: "110g"
    nfs_allow_network: "192.168.5.0/24" # The private IPv4 network on which the worker nodes are located
    nfs_exports:
      - "/data/nfs {{ nfs_allow_network }}(rw,fsid=0,insecure,no_subtree_check,async)"
  roles:
    - storage-volume
    - nfs
  tags:
    - storage

- hosts: all
  roles:
    - docker
  tags:
    - docker

- hosts:
    - role=kube-host
    - role=kube-storage
  vars:
    agent_target_url: 'https://rancherlab.itaas-cloud.com/v1/scripts/0CADE05589B500C4CAB5:1483142400000:XtKPJtzhlpziIOnh3lE9u3gczg' # Enter the target URL here (e.g. 'https://foo.bar.com/v1/scripts/XXXXX:YYY:XXX', as shown in the Rancher UI)
  roles:
    - rancher-agent
  tags:
    - rancher-agent
