FROM microsoft/aspnetcore:2.0-jessie

WORKDIR /app

COPY src/DaaSDemo.UI/bin/Debug/netcoreapp2.0/publish /app

EXPOSE 5000
ENV IN_KUBERNETES=0 PORT=5000 ASPNETCORE_URLS=http://localhost:5000

ENTRYPOINT [ "dotnet", "DaaSDemo.UI.dll" ]
