FROM microsoft/aspnetcore-build:2.0-jessie AS build

WORKDIR /build

COPY DaaS.Demo.sln nuget.config /build/
COPY src/DaaSDemo.UI/package.json src/DaaSDemo.UI/npm-shrinkwrap.json /build/src/DaaSDemo.UI/
COPY src/Common.props /build/src/
COPY src/DaaSDemo.Api/*.csproj /build/src/DaaSDemo.Api/
COPY src/DaaSDemo.Common/*.csproj /build/src/DaaSDemo.Common/
COPY src/DaaSDemo.Data/*.csproj /build/src/DaaSDemo.Data/
COPY src/DaaSDemo.KubeClient/*.csproj /build/src/DaaSDemo.KubeClient/
COPY src/DaaSDemo.Models/*.csproj /build/src/DaaSDemo.Models/
COPY src/DaaSDemo.Provisioning/*.csproj /build/src/DaaSDemo.Provisioning/
COPY src/DaaSDemo.Provisioning.Host/*.csproj /build/src/DaaSDemo.Provisioning.Host/
COPY src/DaaSDemo.SqlExecutor/*.csproj /build/src/DaaSDemo.SqlExecutor/
COPY src/DaaSDemo.SqlExecutor.Client/*.csproj /build/src/DaaSDemo.SqlExecutor.Client/
COPY test/DaaSDemo.TestHarness/*.csproj /build/test/DaaSDemo.TestHarness/
COPY src/DaaSDemo.UI/*.csproj /build/src/DaaSDemo.UI/

ARG VERSION_PREFIX=1.0.0
ARG VERSION_SUFFIX=dev

WORKDIR /build/src/DaaSDemo.UI

RUN npm install --no-optional

WORKDIR /build

RUN dotnet restore /p:VersionPrefix=${VERSION_PREFIX} /p:VersionSuffix=${VERSION_Suffix}

COPY . /build
RUN dotnet publish src/DaaSDemo.UI/DaaSDemo.UI.csproj /p:VersionPrefix=${VERSION_PREFIX} /p:VersionSuffix=${VERSION_SUFFIX} -o /out

FROM microsoft/aspnetcore:2.0-jessie

WORKDIR /app

COPY --from=build /out /app

ENV IN_KUBERNETES=0 ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT [ "dotnet", "DaaSDemo.UI.dll" ]
