---
- name: set host name
  hostname:
    name: "{{ inventory_hostname }}"

- name: persist host name
  template:
    src: hostname.j2
    dest: /etc/hostname

- name: ensure host name can be resolved
  lineinfile:
    dest: /etc/hosts
    line: "{{ private_ipv4 }} {{ inventory_hostname }}"
    state: present

- name: apt-get update
  apt:
    update_cache: true

- name: install pip
  apt:
    name: python-pip
    state: present

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: install CA certificates
  apt:
    name: ca-certificates
    state: present
