---
- name: install NFS
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - nfs-common
    - nfs-kernel-server

- name: NFS exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  register: nfs_exports_copied
  notify: restart NFS

- name: restart NFS
  service:
    name: nfs-kernel-server
    state: restarted
  when: nfs_exports_copied.changed

- name: start NFS
  service:
    name: nfs-kernel-server
    state: started
    enabled: yes
  when: nfs_exports|length
