apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: daas-provisioning
  labels:
    k8s-app: daas-provisioning
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: daas-provisioning

  strategy:
        type: Recreate

  template:
    metadata:
      labels:
        k8s-app: daas-provisioning
    spec:
      serviceAccountName: daas
      terminationGracePeriodSeconds: 60

      containers:
      - name: daas-provisioning
        image: tintoy.azurecr.io/daas/provisioning:1.0.0-dev
        imagePullPolicy: Always
        env:
          - name: IN_KUBERNETES
            value: '1'
          - name: DAAS_Logging__ElasticSearch__EndPoint
            valueFrom:
              configMapKeyRef:
                name: daas
                key: endpoint_elasticsearch_logging
          - name: DAAS_Provisioning__Images__SQL
            valueFrom:
              configMapKeyRef:
                name: daas
                key: image_name_sql
          - name: DAAS_Provisioning__Images__RavenDB
            valueFrom:
              configMapKeyRef:
                name: daas
                key: image_name_ravendb
          - name: DAAS_Prometheus__ApiEndPoint
            valueFrom:
              configMapKeyRef:
                name: daas
                key: endpoint_prometheus
          - name: DAAS_DatabaseProxy__ApiEndPoint
            valueFrom:
              configMapKeyRef:
                name: daas
                key: endpoint_api_database_proxy
          - name: DAAS_Kubernetes__ClusterPublicFQDN
            valueFrom:
              configMapKeyRef:
                name: daas
                key: cluster_fqdn
          - name: DAAS_Kubernetes__PodName
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: DAAS_Kubernetes__KubeNamespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DAAS_Kubernetes__DatabaseStorageClass
            valueFrom:
              configMapKeyRef:
                name: daas
                key: storageclass_data
          - name: DAAS_Database__ConnectionString
            valueFrom:
              configMapKeyRef:
                name: daas
                key: database_server_url
          - name: DAAS_Vault__EndPoint
            valueFrom:
              configMapKeyRef:
                name: daas
                key: endpoint_vault
          - name: DAAS_Vault__Token # TODO: Get this from a Secret instead.
            valueFrom:
              configMapKeyRef:
                name: daas
                key: vault_token
          - name: DAAS_Vault__PkiBasePath
            valueFrom:
              configMapKeyRef:
                name: daas
                key: vault_pki_base_path
          - name: DAAS_Vault__CertificatePolicyName
            valueFrom:
              configMapKeyRef:
                name: daas
                key: vault_certificate_policy_name
        ports:
          - containerPort: 5000
      
      imagePullSecrets:
          - name: daas-registry
