apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: daas-provisioning
  labels:
    k8s-app: daas-provisioning
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: daas-provisioning

  strategy:
        type: Recreate

  template:
    metadata:
      labels:
        k8s-app: daas-provisioning
    spec:
      serviceAccountName: daas
      terminationGracePeriodSeconds: 60

      containers:
      - name: daas-provisioning
        image: tintoy.azurecr.io/daas/provisioning:1.0.0-dev
        imagePullPolicy: Always
        env:
          - name: IN_KUBERNETES
            value: '1'
          - name: DAAS_Logging__ElasticSearch__EndPoint
            valueFrom:
              configMapKeyRef:
                name: daas
                key: endpoint_elasticsearch_logging
          - name: DAAS_Provisioning__Images__SQL
            valueFrom:
              configMapKeyRef:
                name: daas
                key: image_name_sql
          - name: DAAS_Prometheus__ApiEndPoint
            valueFrom:
              configMapKeyRef:
                name: daas
                key: endpoint_prometheus
          - name: DAAS_SQL__ApiEndPoint
            valueFrom:
              configMapKeyRef:
                name: daas
                key: endpoint_api_sql_executor
          - name: DAAS_Kubernetes__ClusterPublicFQDN
            valueFrom:
              configMapKeyRef:
                name: daas
                key: cluster_fqdn
          - name: DAAS_Kubernetes__PodName
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: DAAS_Kubernetes__KubeNamespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DAAS_Kubernetes__SqlStorageClass
            value: 'daas-data'
          - name: DAAS_Database__ConnectionString
            valueFrom:
              configMapKeyRef:
                name: daas
                key: database_server_url
        ports:
          - containerPort: 5000
      
      imagePullSecrets:
          - name: daas-registry
