// <auto-generated />
using DaaSDemo.Data;
using DaaSDemo.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DaaSDemo.Api.Migrations
{
    [DbContext(typeof(Entities))]
    [Migration("20171110221129_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DaaSDemo.Models.Data.DatabaseInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Action");

                    b.Property<string>("DatabasePassword")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("DatabaseServerId");

                    b.Property<string>("DatabaseUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseServerId");

                    b.HasIndex("Name");

                    b.ToTable("DatabaseInstance");
                });

            modelBuilder.Entity("DaaSDemo.Models.Data.DatabaseServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Action");

                    b.Property<string>("AdminPassword")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Phase");

                    b.Property<string>("PublicFQDN")
                        .HasMaxLength(100);

                    b.Property<int?>("PublicPort");

                    b.Property<int>("Status");

                    b.Property<int>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("TenantId");

                    b.ToTable("DatabaseServer");
                });

            modelBuilder.Entity("DaaSDemo.Models.Data.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("DaaSDemo.Models.Data.DatabaseInstance", b =>
                {
                    b.HasOne("DaaSDemo.Models.Data.DatabaseServer", "DatabaseServer")
                        .WithMany("Databases")
                        .HasForeignKey("DatabaseServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DaaSDemo.Models.Data.DatabaseServer", b =>
                {
                    b.HasOne("DaaSDemo.Models.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
