apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ravendb
  labels:
    k8s-app: ravendb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ravendb

  strategy:
        type: Recreate

  template:
    metadata:
      labels:
        k8s-app: ravendb
    spec:
      serviceAccountName: daas
      terminationGracePeriodSeconds: 60

      containers:
      - name: ravendb
        image: ravendb/ravendb:ubuntu-latest
        imagePullPolicy: IfNotPresent
        
        env:
          - name: UNSECURED_ACCESS_ALLOWED
            value: 'PublicNetwork'

        volumeMounts:
          - name: data
            mountPath: /databases

        ports:
          - name: https
            containerPort: 8080
          - name: tcp
            containerPort: 38888

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ravendb-data

---

# Externally-facing service
apiVersion: v1
kind: Service
metadata:
  name: ravendb
  labels:
    k8s-app: ravendb
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 31880
    targetPort: 8080
    protocol: TCP
  - name: tcp
    port: 38888
    nodePort: 31888
    targetPort: 38888
    protocol: TCP
  selector:
    k8s-app: ravendb
