apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ravendb-data
  labels:
    k8s-app: ravendb
spec:
  storageClassName: raven-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
