apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: daas-vault-external
spec:
  ports:
  - name: vault
    port: 8200
    nodePort: 31820
    targetPort: 8200
    protocol: TCP
  selector:
    app: vault
  type: NodePort
