apiVersion: v1
kind: Pod
metadata:
  name: temp1
  namespace: default
  labels:
    app: wordpress
spec:
  nodeName: kube-host-01
  containers:
  - command:
    - 'sleep'
    - '500'
    image: ubuntu:trusty
    imagePullPolicy: IfNotPresent
    name: temp1
    volumeMounts:
    - name: mysql-persistent-storage
      mountPath: /mysql-data
  restartPolicy: Never
  terminationGracePeriodSeconds: 5
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: mysql-pv-claim
