apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-rook-data-claim
  labels:
    app: wordpress
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
