apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-data
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # Update this to point to your NFS server
    server: 192.168.5.30
    path: "/"
