---
- hosts: localhost
  gather_facts: no
  tasks:
    # Change concurrently with the required ansible version in requirements.txt
    - name: check for compatible Ansible version
      when: >
        ansible_version["string"] | version_compare("2", "<")
      fail:
        msg: >
          Ansible 2.x is required.

- hosts: all
  gather_facts: yes
  tasks:
    - name: check for compatible Unbuntu version
      when: ansible_distribution_version | version_compare("14.04", "<")
      fail:
        msg: >
          Your hosts don't appear to be running a compatible version of Unbuntu.
          Please run the playbook playbooks/upgrade-packages.yml before
          continuing.

    - name: check for compatible kernel version
      when: >
        ansible_kernel | version_compare("3.10.0-327", "<")
      fail:
        msg: >
          Your hosts don't appear to be running a compatible version of the
          Linux kernel. Please run the playbook playbooks/upgrade-packages.yml
          before continuing.
