--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Elasticsearch
  name: elasticsearch-logging
  namespace: kube-system
spec: 
  ports: 
    - port: 9200
      protocol: TCP
      targetPort: db
  selector: 
    k8s-app: elasticsearch-logging
  type: ClusterIP
