apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kibana-logging
  name: kibana-logging
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch-logging:9200
        image: kibana:4.6.4
        imagePullPolicy: IfNotPresent
        name: kibana-logging
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        resources: {}

--- 

# Externally-facing service
apiVersion: v1
kind: Service
metadata: 
  labels: 
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Kibana
  name: kibana-logging
  namespace: kube-system
spec: 
  ports: 
    - targetPort: ui
      nodePort: 30560
      port: 5601
      protocol: TCP
  selector: 
    k8s-app: kibana-logging
  type: NodePort
